# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1
context:
  name: markdownify-mcp-server
  version: "0.1.13"
  python_min: '3.13'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/markdownify_mcp_server-${{ version }}.tar.gz
  sha256: e3664a317dcf4267771d8031f2338a6636df411f0f8fc002d269fba82d8a8fb4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - markdownify-mcp-server = markdownify_mcp.server:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - markitdown >=0.1.1
    - mcp >=1.6.0

tests:
  - python:
      imports:
        - markdownify_mcp
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - markdownify-mcp-server --help

about:
  summary: A Model Context Protocol server for converting almost anything to Markdown.
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/markdownify-mcp-server/
  repository: https://github.com/zcaceres/markdownify-mcp

extra:
  recipe-maintainers:
    - rxm7706
